version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./web:/var/www/html
      - ./web/conf:/etc/nginx/conf.d
    ports:
      - 80:80
  fpm:
    build: ./fpm
    volumes:
      - ./fpm:/var/www/html
    ports:
      - 9000:9000
